version: "3"

volumes:
  postgres_data_sc: {}

services:
  server:
    image: node:12.16.3
    stdin_open: true
    volumes:
      - .:/api
    working_dir: /api
    ports:
      - 3333:3333

  db-postgres:
    ports:
      - 5432:5432
    volumes:
      - ./postgres/backups:/backups

  cache-redis:
    ports:
      - 6379:6379
